### PR TITLE
Add pointer cursor to close buttons

### PR DESCRIPTION
**Pull request by WanaByte**
This adds pointer instruction to the CSS file since it doesn't seem to be displaying properly as a pointer.

### CODE REVIEW

**Comment by ahmadnassri** [comment]
actually, I shouldn't have merged that, this modifies the bootstrap css file which is 3rd party repo (http://twitter.github.com/bootstrap/) ... it should be done in the REST Console `style.css` ...

now to figure out how to undo a merge in github ...

**Comment by ahmadnassri** [comment]
well now, that wasn't very hard, the proper place for this is under style.css, if you wish you can add it there, or I will add it in the next release.

thanks :)

**Comment by WanaByte** [comment]
Sorry about that. I grepped for `.close` and only turned up that one location. 

I figured rather than file issues all day, I'd help contribute. `;)`

**Comment by ahmadnassri** [comment]
and we love contributions :) thank you!

**Pull request merged**
